/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Azka
 */
public class GUI extends javax.swing.JFrame {
//Varibles necesarias para conectarse y poder poner los paneles nuevos
    variablesbool var = new variablesbool();
    panel2 pn2 = new panel2();
    Panel0 pn0 = new Panel0();
    conectar cc = new conectar();
    Connection cn = cc.conexion();
    Graphics g;
    public int x = 228, y = 172;
    protected int diametro = 30;
    public boolean juego = true;
    
    tiempo time;
    Thread lanzador;
    protected boolean perder = false;
    protected boolean enemigos = true;
    Juego w;
    public JLabel tequiero;
    Lanzador lanz;
//Detecta la colision de la bola, para poder comparar y ver si hay gameover o no
    public Rectangle colision() {
        Rectangle bola;
        bola = new Rectangle(x, y, diametro, diametro);
        return bola;

    }

    public int TengoX() {
        return x;
    }

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        taim.setVisible(false);
        //Se pone el panelprincipal
        g = panelpri.getGraphics();
        this.setLocation(400, 0);
        setSize(390, 768);
        iniciob.setEnabled(false);
        bloqueob.setEnabled(false);
        //Se ve que color de iphone es el que está en la base de datos, y dependiendo de su valor, se compara ara poner el color correspondiente
        ResultSet resultado = pn0.seleccionar("coloriphone", "iphone");
        try {
            if (resultado.next()) {
                String o = resultado.getString("iphone");
                int O = Integer.parseInt(o);
                if (O == 1) {
                    fondoiphone.setIcon(new ImageIcon(getClass().getResource("/hola/iphone (1) (4).png")));
                }
                if (O == 2) {
                    fondoiphone.setIcon(new ImageIcon(getClass().getResource("/hola/iphone (1).png")));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR HIPER RARO");
        }
        this.setFocusable(true);

        /*pn0.setSize(330, 580);
        panelpri.removeAll();
        panelpri.add(pn0,BorderLayout.CENTER);
        panelpri.revalidate();
        panelpri.repaint();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciob = new javax.swing.JButton();
        panelpri = new javax.swing.JPanel();
        ingresec = new javax.swing.JLabel();
        taim = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jcontra = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        iniciob2 = new javax.swing.JButton();
        bloqueob = new javax.swing.JButton();
        fondoiphone = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO PROGRAMACIÓN CONCURRENTE");
        setLocation(new java.awt.Point(500, 500));
        setMaximumSize(new java.awt.Dimension(509, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(509, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pro/A VER/transp.png"))); // NOI18N
        iniciob.setBorder(null);
        iniciob.setBorderPainted(false);
        iniciob.setContentAreaFilled(false);
        iniciob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciob.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iniciob.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iniciob.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iniciob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciobActionPerformed(evt);
            }
        });
        getContentPane().add(iniciob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, 60, 60));

        panelpri.setBackground(new java.awt.Color(255, 255, 255));
        panelpri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        panelpri.setPreferredSize(new java.awt.Dimension(283, 472));

        ingresec.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 12)); // NOI18N
        ingresec.setForeground(new java.awt.Color(255, 255, 255));
        ingresec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ingresec.setText("INGRESE CONTRASEÑA");

        taim.setText("0");
        taim.setFocusable(false);

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton1.setText("3");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton2.setText("1");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton2.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton4.setText("2");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton5.setText("5");
        jButton5.setToolTipText("");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton6.setText("4");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton7.setText("6");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton14.setText("INV");
        jButton14.setBorder(null);
        jButton14.setBorderPainted(false);
        jButton14.setContentAreaFilled(false);
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton8.setText("ENTER");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton9.setText("7");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton10.setText("9");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton11.setText("8");
        jButton11.setBorder(null);
        jButton11.setBorderPainted(false);
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton13.setText("0");
        jButton13.setBorder(null);
        jButton13.setBorderPainted(false);
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jcontra.setEditable(false);
        jcontra.setBackground(new java.awt.Color(51, 51, 51));
        jcontra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jcontra.setForeground(new java.awt.Color(255, 255, 255));
        jcontra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jcontra.setAutoscrolls(false);
        jcontra.setBorder(null);
        jcontra.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/fondopre.jpg"))); // NOI18N

        jButton12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros.png"))); // NOI18N
        jButton12.setText("ENTER");
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);
        jButton12.setContentAreaFilled(false);
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/hola/numeros (1).png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelpriLayout = new javax.swing.GroupLayout(panelpri);
        panelpri.setLayout(panelpriLayout);
        panelpriLayout.setHorizontalGroup(
            panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ingresec, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelpriLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(taim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelpriLayout.setVerticalGroup(
            panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(ingresec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelpriLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpriLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpriLayout.createSequentialGroup()
                        .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelpriLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpriLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelpriLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelpriLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(panelpriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(10, 10, 10)
                .addComponent(taim))
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelpriLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(panelpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 323, 580));

        iniciob2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pro/A VER/transp.png"))); // NOI18N
        iniciob2.setBorder(null);
        iniciob2.setBorderPainted(false);
        iniciob2.setContentAreaFilled(false);
        iniciob2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciob2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iniciob2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        iniciob2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        iniciob2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciob2ActionPerformed(evt);
            }
        });
        getContentPane().add(iniciob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 20, 110));

        bloqueob.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pro/A VER/transp.png"))); // NOI18N
        bloqueob.setBorder(null);
        bloqueob.setBorderPainted(false);
        bloqueob.setContentAreaFilled(false);
        bloqueob.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bloqueob.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloqueob.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bloqueob.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bloqueob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bloqueobMousePressed(evt);
            }
        });
        bloqueob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloqueobActionPerformed(evt);
            }
        });
        getContentPane().add(bloqueob, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 30, 60));

        fondoiphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pro/A VER/iphone (1).png"))); // NOI18N
        getContentPane().add(fondoiphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -2, 430, 760));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciobActionPerformed
        // TODO add your handling code here:
        //Se da acceso al panel0
        Panel0 pn0 = new Panel0();

        pn0.setSize(323, 580);
        panelpri.removeAll();
        panelpri.add(pn0, BorderLayout.CENTER);
        panelpri.revalidate();
        panelpri.repaint();
    }//GEN-LAST:event_iniciobActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "3");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "1");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "2");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "4");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "6");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //compara el numero concatenado si es igual a la contraseña, y dependiendo si es igual, da acceso a la siguiente pantalla
        String a = jcontra.getText();

        try {
            String sql = "";
            sql = ("SELECT * FROM contraseña");
            PreparedStatement sen = cn.prepareStatement(sql);
            ResultSet resultado = sen.executeQuery();
            if (resultado.next()) {
                if (resultado.getString(1).equals(a)) {
                    JOptionPane.showMessageDialog(this, "Has accesado como usuario");
                    var.admin=false;
                    var.invitado=false;
                    var.usuario = true;
                    iniciob.setEnabled(true);
                    bloqueob.setEnabled(true);
                    Panel0 pn0 = new Panel0();
                    pn0.setSize(323, 580);
                    panelpri.removeAll();
                    panelpri.add(pn0, BorderLayout.CENTER);
                    panelpri.revalidate();
                    panelpri.repaint();

                    System.out.println("HOla");
                    //System.out.println(resultado.getString(2));
                } else if (resultado.getString(2).equals(a)) {
                    JOptionPane.showMessageDialog(this,"Has accesado como Admin");
                    var.admin=true;
                    var.invitado=false;
                    var.usuario = false;
                    iniciob.setEnabled(true);
                    bloqueob.setEnabled(true);
                    Panel0 pn0 = new Panel0();
                    pn0.setSize(323, 580);
                    panelpri.removeAll();
                    panelpri.add(pn0, BorderLayout.CENTER);
                    panelpri.revalidate();
                    panelpri.repaint();

                    System.out.println("Hola 2");
                } else if (resultado.getString(3).equals(a)) {
                    JOptionPane.showMessageDialog(this,"Has accesado como Invitado");
                    var.admin=false;
                    var.invitado=true;
                    var.usuario = false;
                    iniciob.setEnabled(true);
                    bloqueob.setEnabled(true);
                    Panel0 pn0 = new Panel0();
                    pn0.setSize(323, 580);
                    panelpri.removeAll();
                    panelpri.add(pn0, BorderLayout.CENTER);
                    panelpri.revalidate();
                    panelpri.repaint();

                    System.out.println("Hola 3");
                } else {
                    ingresec.setText("CONTRASEÑA INCORRECTA, INTENTE DE NUEVO");
                    jcontra.setText("");
                }

            } else {
                ingresec.setText("CONTRASEÑA INCORRECTA, INTENTE DE NUEVOO");
                jcontra.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NullPointerException ex){
            System.out.println("hol");
        }
        /*if (contra.equals(a)) {
            Panel0 pn0 = new Panel0();
            pn0.setSize(330, 580);
            panelpri.removeAll();
            panelpri.add(pn0, BorderLayout.CENTER);
            panelpri.revalidate();
            panelpri.repaint();
            

            
        } else {
            ingresec.setText("CONTRASEÑA INCORRECTA, INTENTE DE NUEVO");
            jcontra.setText("");
        }*/
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "7");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "9");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "8");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        //concatena el numero
        jcontra.setText(jcontra.getText() + "0");


    }//GEN-LAST:event_jButton13ActionPerformed

    private void bloqueobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloqueobActionPerformed
        // Cuando se bloquea el celular, reinicia toda el programa
        Sonido.CHUEK.stop();
        Sonido.LINK.stop();
        dispose();
        GUI.main(null);

    }//GEN-LAST:event_bloqueobActionPerformed

    private void iniciob2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciob2ActionPerformed
        //Botón que hace que se cierre el programa
        System.exit(0);

    }//GEN-LAST:event_iniciob2ActionPerformed

    private void bloqueobMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bloqueobMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_bloqueobMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //Juego donde enemigos es la variable que dice si hay enemigos y da comienzo al juego
//        if (enemigos) {
//            Color panel = new Color(204, 255, 255);
//            panelpri.setBackground(panel);
//            enemigos ene = new enemigos(this, panelpri);
//            ene.setG(g);
//            ene.start();
//            lanz = new Lanzador(this.ene, panelpri, this);
//            lanz.setG(g);
//            lanz.start();
//            Sonido.LINK.loop();
//            taim.setVisible(true);
//
//            tequiero = new JLabel("0");
//            tequiero.setVisible(true);
//
//            tequiero.setBounds(161, 290, 100, 100);
//            panelpri.add(tequiero);
//
//            tiempo time = new tiempo(this);
//            time.setOk(tequiero);
//            time.start();
//            enemigos = false;
//        }
//        
//        //Keylistener para que se mueva la bola
//        if (juego) {
//            System.out.println("o");
//            g.setColor(panelpri.getBackground());
//            g.fillRect(x, y, diametro, diametro);
//
//            if (evt.getKeyCode() == KeyEvent.VK_LEFT && x != 3) {
//
//                x -= 15;
//            }
//            if (evt.getKeyCode() == KeyEvent.VK_RIGHT && x != 303) {
//
//                x += 15;
//            }
//            if (evt.getKeyCode() == KeyEvent.VK_UP && y != 7) {
//
//                y -= 15;
//            }
//            if (evt.getKeyCode() == KeyEvent.VK_DOWN && y != 547) {
//
//                y += 15;
//            }
//            if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
//
//                enemigos ene = new enemigos(this, panelpri);
//                ene.setG(g);
//                ene.start();
//
//            }
//            g.setColor(Color.darkGray);
//            g.fillOval(x, y, diametro, diametro);
//            System.out.println("X=" + x + " Y=" + y);
//        }
    }//GEN-LAST:event_formKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        //Da focus al juego
        juego = true;
        this.setFocusable(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        String a = "0";

        try {
            String sql = "";
            sql = ("SELECT * FROM contraseña");
            PreparedStatement sen = cn.prepareStatement(sql);
            ResultSet resultado = sen.executeQuery();
            if (resultado.next()) {
                if (resultado.getString(1).equals(a)) {
                    JOptionPane.showMessageDialog(this, "Has accesado como usuario");
                    var.admin=false;
                    var.invitado=false;
                    var.usuario = true;
                    iniciob.setEnabled(true);
                    bloqueob.setEnabled(true);
                    Panel0 pn0 = new Panel0();
                    pn0.setSize(323, 580);
                    panelpri.removeAll();
                    panelpri.add(pn0, BorderLayout.CENTER);
                    panelpri.revalidate();
                    panelpri.repaint();

                    System.out.println("HOla");
                    //System.out.println(resultado.getString(2));
                } else if (resultado.getString(2).equals(a)) {
                    JOptionPane.showMessageDialog(this,"Has accesado como Admin");
                    var.admin=true;
                    var.invitado=false;
                    var.usuario = false;
                    iniciob.setEnabled(true);
                    bloqueob.setEnabled(true);
                    Panel0 pn0 = new Panel0();
                    pn0.setSize(323, 580);
                    panelpri.removeAll();
                    panelpri.add(pn0, BorderLayout.CENTER);
                    panelpri.revalidate();
                    panelpri.repaint();

                    System.out.println("Hola 2");
                } else if (resultado.getString(3).equals(a)) {
                    JOptionPane.showMessageDialog(this,"Has accesado como Invitado");
                    var.admin=false;
                    var.invitado=true;
                    var.usuario = false;
                    iniciob.setEnabled(true);
                    bloqueob.setEnabled(true);
                    Panel0 pn0 = new Panel0();
                    pn0.setSize(323, 580);
                    panelpri.removeAll();
                    panelpri.add(pn0, BorderLayout.CENTER);
                    panelpri.revalidate();
                    panelpri.repaint();

                    System.out.println("Hola 3");
                } else {
                    ingresec.setText("CONTRASEÑA INCORRECTA, INTENTE DE NUEVO");
                    jcontra.setText("");
                }

            } else {
                ingresec.setText("CONTRASEÑA INCORRECTA, INTENTE DE NUEVOO");
                jcontra.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NullPointerException ex){
            System.out.println("hol");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloqueob;
    private javax.swing.JLabel fondoiphone;
    private javax.swing.JLabel ingresec;
    private javax.swing.JButton iniciob;
    private javax.swing.JButton iniciob2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jcontra;
    public static javax.swing.JPanel panelpri;
    private javax.swing.JLabel taim;
    // End of variables declaration//GEN-END:variables
}
