/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro;

import static Pro.GUI.panelpri;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Azka
 */
public class Juego extends javax.swing.JPanel implements KeyListener{
Graphics g;
protected int x=228,y=172;
protected int diametro= 30;
enemigos1 ene;
tiempo time;
Thread lanzador;
protected boolean juego =true;
protected boolean perder=false;
Lanzador lanz;
GUI ok;
conectar cc = new conectar();
Connection con = cc.conexion();
    PreparedStatement instruccion;
    ResultSet datos;
    DefaultListModel model = new DefaultListModel();

public Rectangle colision(){
   Rectangle bola;
   bola = new Rectangle(x,y,diametro,diametro);
   return bola;
   
}
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        ok = new GUI();
    try {
        instruccion = con.prepareStatement("SELECT * FROM juegobola");
        datos = instruccion.executeQuery();
        
        ResultSetMetaData rsmd = datos.getMetaData();
        int col= rsmd.getColumnCount();
        DefaultTableModel modelo = new DefaultTableModel();
        for(int j=1;j<=col;j++){
            modelo.addColumn(rsmd.getColumnLabel(j));
        }
        while(datos.next()){
            String filas[]=new String[5];
            for(int i = 0;i<5;i++){
                filas[i]=datos.getString(i+1);
            }
            
            System.out.println(datos.getString(5));
            modelo.addRow(filas);
            lista.setModel(modelo);
        }
        
        datos.close();
    } catch (SQLException ex) {
        Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tiempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        texta = new javax.swing.JTextArea();
        blok = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("OPRIME AQUÍ PARA EMPEZAR");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tiempo.setText("0");

        jLabel1.setText("INSTRUCCIONES:");

        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Longitud", "Puntaje", "Fechahora"
            }
        ));
        jScrollPane2.setViewportView(lista);

        texta.setEditable(false);
        texta.setColumns(20);
        texta.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        texta.setRows(5);
        texta.setText("Cuando oprimas empezar\nsaldrá una bola, ¡muevete\ncon el teclado e intenta no tocar los \ncuadros y así obtener el mayor\ntiempo posible!");
        texta.setAutoscrolls(false);
        texta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        texta.setFocusable(false);
        texta.setRequestFocusEnabled(false);

        blok.setText("*Si desea salir, bloquee el teléfono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(texta, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel1))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(blok)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(tiempo)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
//g.clearRect(x, y, diametro, diametro);
        g.setColor(this.getBackground());
        g.fillRect(x, y, diametro, diametro);
       
        if (evt.getKeyCode()==KeyEvent.VK_LEFT&&x!=3){
            
            
            x-=15;
        }
        if (evt.getKeyCode()==KeyEvent.VK_RIGHT&&x!=303){
            
            
            x+=15;
        }
        if (evt.getKeyCode()==KeyEvent.VK_UP&&y!=7){
            
            
            y-=15;
        }
        if (evt.getKeyCode()==KeyEvent.VK_DOWN&&y!=547){
            
            
            y+=15;
        }
        if (evt.getKeyCode()==KeyEvent.VK_SPACE){
            enemigos1 ene = new enemigos1(this,ok);
            ene.setG(g);
        ene.start();
            
        }
        g.setColor(Color.darkGray);
        g.fillOval(x, y, diametro, diametro);
        System.out.println("X="+x+" Y="+y);
        
        
    }//GEN-LAST:event_formKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        blok.setVisible(false);
         jScrollPane2.setVisible(false);
        lista.setVisible(false);
       texta.setVisible(false);
        jLabel1.setVisible(false);
       jButton1.setVisible(false);
       jButton1.setEnabled(false);
        this.requestFocus();
         Sonido.LINK.loop();
        time = new tiempo(this);
        time.setOk(tiempo);
        time.start();
        enemigos1 ene = new enemigos1(this,ok);
        
        g = this.getGraphics();
        g.setColor(Color.darkGray);
        g.fillOval(x, y, diametro, diametro);
        ene.setG(g);
        ene.start();
        

       lanz = new Lanzador(ene,this,ok);
       lanz.setG(g);
       lanz.start();
       
//        this.time = new tiempo(ok);
//        time.setOk(this.tiempo);
//        time.start();
//        ok.setFocusable(true);
//        
        
        
        
        
        
        /*System.out.println("ok: "+ok.TengoX());
        this.time = new tiempo(ok);
        time.setOk(this.tiempo);
        time.start();
        ene = new enemigos(ok,ok.panelpri);
       time.setOk(this.tiempo);
        time.start();
        ok.juego=false;
        g= this.getGraphics();
        ene.setG(g);
        ene.start();
        time.setOk(this.tiempo);
        time.start();
       lanz = new Lanzador(ene,this,ok);
       lanz.setG(g);
       lanz.start();*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void keyTyped(KeyEvent e) {
        System.out.println("HOla");
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lista;
    private javax.swing.JTextArea texta;
    public javax.swing.JLabel tiempo;
    // End of variables declaration//GEN-END:variables
}
