/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pro;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Azka
 */
public class Juego2 extends javax.swing.JPanel implements KeyListener{
    conectar cc = new conectar();
Connection con = cc.conexion();
PreparedStatement instruccion;
    ResultSet datos;
    DefaultListModel model = new DefaultListModel();
    Graphics g;
    GUI ok;

    public int x = 2, xCambio = 0;
    HiloBola b;
    
        public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }
    

    public void cargabola() {
this.b = new HiloBola(x, boundess(),this,ok);
        
        b.setBola(Color.black);
        b.setFondo(getBackground());
        b.setW(getWidth());
        b.setH(getHeight());
        b.setCoor(lp);
        b.setG(g);
        b.setScore(puntos);

        b.start();
        
        this.requestFocus();
        
    }

    /**
     * Creates new form Juego2
     */
    public Juego2() {
        initComponents();
        Sonido.CHUEK.loop();
        puntos.setVisible(false);
        lp.setVisible(false);
        ok = new GUI();
             
    try {
        instruccion = con.prepareStatement("SELECT * FROM juegotennis");
        datos = instruccion.executeQuery();
        
        ResultSetMetaData rsmd = datos.getMetaData();
        int col= rsmd.getColumnCount();
        DefaultTableModel modelo = new DefaultTableModel();
        for(int j=1;j<=col;j++){
            modelo.addColumn(rsmd.getColumnLabel(j));
        }
        while(datos.next()){
            String filas[]=new String[4];
            for(int i = 0;i<4;i++){
                filas[i]=datos.getString(i+1);
            }
            
            System.out.println(datos.getString(4));
            modelo.addRow(filas);
            lista.setModel(modelo);
        }
        
        datos.close();
    } catch (SQLException ex) {
        Logger.getLogger(Juego.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lp = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        texta = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 255, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lp.setText("0");

        puntos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        puntos.setText("0");

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("OPRIME AQUÍ PARA EMPEZAR");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("INSTRUCCIONES:");

        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Longitud", "Puntaje", "Fechahora"
            }
        ));
        jScrollPane2.setViewportView(lista);

        texta.setEditable(false);
        texta.setColumns(20);
        texta.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        texta.setRows(5);
        texta.setText("Cuando oprimas empezar\nsaldrá una bola, ¡muevete\ncon el teclado e intenta hacer que la \npelota rebote en la raqueta y así\n obtener la mayor puntuación posible!");
        texta.setAutoscrolls(false);
        texta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        texta.setFocusable(false);
        texta.setRequestFocusEnabled(false);

        jLabel2.setText("*Si desea salir, bloquee el teléfono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(texta, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(120, 120, 120)
                                    .addComponent(jLabel1))))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(puntos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(texta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(62, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
          System.out.println("ok");
          g.setColor(this.getBackground());
                
       g.fillRect(x, 560, 75, 15);
        if (evt.getKeyCode() == KeyEvent.VK_LEFT&&x!=2) {
            x = x - 20;

        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT&&x!=242) {
            x = x + 20;

        }
        g.setColor(Color.red);
        g.fillRect(x, 560, 75, 15);
        lp.setText("" + x);
    }//GEN-LAST:event_formKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel2.setVisible(false);
        puntos.setVisible(true);
        lp.setVisible(true);
        jScrollPane2.setVisible(false);
        lista.setVisible(false);
        texta.setVisible(false);
        jLabel1.setVisible(false);
        jButton2.setVisible(false);
        jButton2.setEnabled(false);
        this.requestFocus();
        

        g = this.getGraphics();

        cargabola();


        //        this.time = new tiempo(ok);
        //        time.setOk(this.tiempo);
        //        time.start();
        //        ok.setFocusable(true);
        //

        /*System.out.println("ok: "+ok.TengoX());
        this.time = new tiempo(ok);
        time.setOk(this.tiempo);
        time.start();
        ene = new enemigos(ok,ok.panelpri);
        time.setOk(this.tiempo);
        time.start();
        ok.juego=false;
        g= this.getGraphics();
        ene.setG(g);
        ene.start();
        time.setOk(this.tiempo);
        time.start();
        lanz = new Lanzador(ene,this,ok);
        lanz.setG(g);
        lanz.start();*/

    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
      
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
    public Rectangle boundess() {
        return new Rectangle(x, 560, 75, 15);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lista;
    private javax.swing.JLabel lp;
    protected javax.swing.JLabel puntos;
    private javax.swing.JTextArea texta;
    // End of variables declaration//GEN-END:variables
}
